FROM sk1064/medivista:latest


RUN rm /usr/bin/python3 && \
    ln -s /usr/bin/python3.8 /usr/bin/python3 && \
    ln -s /usr/bin/python3.8 /usr/bin/python

RUN python3 -m pip install --upgrade pip

# install pytorch
# torch < 2.0.0
RUN python3 -m pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

# install requirements
COPY requirements.txt /env/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /env/requirements.txt

# GitHub installations:
RUN python3 -m pip install git+https://github.com/zhennongchen/CTProjector.git 


COPY entrypoint.sh /env/entrypoint.sh
RUN chmod +x /env/entrypoint.sh

COPY compile.sh /env/compile.sh
RUN chmod +x /env/compile.sh

ENTRYPOINT [ "/env/entrypoint.sh" ]