FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu20.04

RUN apt-get -y update 
RUN apt-get install -y \
        python3.8 \
        python3-pip \
        dcm2niix \
        wget \
        git \
        git-lfs && \
    apt clean

RUN rm /usr/bin/python3 && \
ln -s /usr/bin/python3.8 /usr/bin/python3 && \
ln -s /usr/bin/python3.8 /usr/bin/python

RUN python3 -m pip install --upgrade pip

RUN pip install --no-cache-dir torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

COPY requirements.txt /env/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /env/requirements.txt

COPY entrypoint.sh /env/entrypoint.sh
RUN chmod +x /env/entrypoint.sh

ENTRYPOINT [ "/env/entrypoint.sh" ]