FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime

RUN apt-get -y update && apt-get install -y \
        dcm2niix \
        wget \
        git \
        git-lfs && \
    apt clean

COPY requirements.txt /env/requirements.txt
# RUN pip3 install --upgrade pip
RUN python3 -m pip install --no-cache-dir -r /env/requirements.txt

COPY entrypoint.sh /env/entrypoint.sh
RUN chmod +x /env/entrypoint.sh

ENTRYPOINT [ "/env/entrypoint.sh" ]